# Generated by Django 4.0.4 on 2022-06-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='media/post_thumbnail/%Y/%M/%d'),
            preserve_default=False,
        ),
    ]
