# Generated by Django 3.2.7 on 2021-12-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_picture',
        ),
    ]
